# Use new container infrastructure to enable caching
sudo: false

language: java

jdk:
  - oraclejdk8

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev
      - git

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
# Build dependencies
- git clone --recursive https://github.com/rahulmutt/ghcvm
- cd ghcvm
- stack --no-terminal --install-ghc test --only-dependencies
- travis_wait ./install.sh

script:
# Build the package, its tests, and its docs and run the tests
- cd ../packages/
- ./Test.hs

